name: URL for files updated on Pull Request
description: Comments a pull request with url to check for updated files
branding:
  icon: align-left
  color: blue
inputs:
  token:
    required: true
    description: Access token to the repository.
runs:
  using: node16
  main: dist/index.js