name: Compress Images Nightly
on:
  workflow_call:
    inputs:
      pr-title:
        description: 'Title of the Pull Request to create'
        type: string
        default: 'feat: Compressed Images'
      branch-name:
        description: 'Name of the branch to create'
        type: string
        default: 'feat/compressed-images'
    secrets:
      github-token:
        description: 'GitHub token for authentication'
        required: true

jobs:
  compress:
    name: calibreapp/image-actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Compress Images
        id: calibre
        uses: calibreapp/image-actions@main
        with:
          githubToken: ${{ secrets.github-token }}
          compressOnly: true

      - name: Create New Pull Request If Needed
        if: steps.calibre.outputs.markdown != ''
        uses: peter-evans/create-pull-request@v4
        with:
          title: ${{ inputs.pr-title }} for ${{ github.ref_name }}
          branch-suffix: 'timestamp'
          commit-message: 'feat: Compressed Images'
          branch: ${{ inputs.branch-name }}
          body: ${{ steps.calibre.outputs.markdown }}