name: Broken link check v2
on: 
  workflow_dispatch:
    inputs:
      siteUrl:
          description: url to check
          default: 'https://documentation.bonitasoft.com/bonita/2022.2'
          required: true 

jobs:
  broken_link_checker_job_v2:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
      - name: Check for broken links
        uses: ruzickap/action-my-broken-link-checker@v2
        with:
          url: ${{github.event.inputs.siteUrl}}
          cmd_params: "--one-page-only --max-connections=3 --color=always --buffer-size=8192"  # Check just one page
