name: Nightly Image Compression
on:
  workflow_dispatch:

jobs:
  compress-images:
    uses: ./.github/workflows/_reusable_compress_images_nightly.yml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}