name: List updates_files on pull request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  anotherWayToListFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Glob match
        uses: tj-actions/glob@v16
        id: glob
        with:
          files: |
            modules/**
      - name: Run if file exist
        if: ${{ steps.glob.outputs.paths != ''}}
        uses: tj-actions/glob@v16
        id: glob-result-step
        with:
          files: |
            toto/**
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            modules/**
      - name: Get files url
        uses: actions/github-script@v6
        id: set-result
        env:
          FILES: ${{steps.changed-files.outputs.all_changed_files}}
          SITE_URL: 'http://localhost'
          COMPONENT_NAME: 'bonita'
        with:
          script: |            
            const script = require('./.github/comments-with-url-links.js');
            return await script.prepareUrlLinks({github, context})
          result-encoding: string
      - name: Create or update comments
        uses: actions/github-script@v6
        env:
          LINKS: ${{steps.set-result.outputs.result}}
          RENAMED_FILES: ${{steps.changed-files.outputs.renamed_files}}
          HAS_DELETED_FILES: ${{steps.changed-files.outputs.any_deleted}}
        with:
          script: |
            const script = require('./.github/comments-with-url-links.js');
            let commentId = await script.createOrUpdateComments({github, context})
            console.log('commentId',commentId);
            return commentId;
          result-encoding: string

