name: List updates_files on pull request

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  anotherWayToListFiles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            modules/**
      - name: List all changed files
        id: build-urls
        run: |
          urls=""
          for file in ${{steps.changed-files.outputs.all_changed_and_modified_files}}; do
            #Read the split words into an array based on / delimiter
            IFS='/'
            read -a strarr <<< "$file"
            IFS=''
            #unset "modules" from array
            strarr=("${strarr[@]:1}")
            #Get module name if not ROOT
            [[ ${strarr[0]} = "ROOT" ]] && moduleName="/" || moduleName="/${strarr[0]}/"
            #Last element 'page.name'
            pageName=${strarr[${#strarr[@]} - 1]}             
            urls+="- https://documenation.bonitasoft.com/bonita/${{github.base_ref}}${moduleName}${pageName%.*}
          "
          done          
          echo "updated_files_url=$urls" >> $GITHUB_OUTPUT
          echo $urls
      - name: Find Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: ''## Pull request files update :memo:'
      - name: Render template
        id: template
        uses: chuhlomin/render-template@v1.4
        with:
          template: .github/comment-template.md
          vars: |
            urlFiles: ${{ steps.build-urls.outputs.updated_files_url }}
      - name: Create or update comment
        uses: peter-evans/create-or-update-comment@v2
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          body: ${{ steps.template.outputs.result }}
          edit-mode: replace

