name: Bump Npm version

on:  
  workflow_dispatch:
   inputs:
      version:
        description: <newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>
        default: patch
        required: true      


jobs:
  deploy:
    name: Bump NPM version
    runs-on: ubuntu-20.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1 
        with:
          node-version: '14'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci      

      - name: 'change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{github.event.inputs.version}}          
          git-tag-version: 'true'
