name: Bump Npm version

on:  
  workflow_dispatch:
   inputs:
      version:
        description: <newversion> | major | minor | patch | premajor | preminor | prepatch | prerelease [--preid=<prerelease-id>
        default: patch
        required: true      


jobs:
  deploy:
    name: Bump NPM version
    runs-on: ubuntu-20.04    

    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        run: git config --global user.email "you@example.com"
        run: git config --global user.name "Your Name"

      - name: Install Node
        uses: actions/setup-node@v1 
        with:
          node-version: '14'          

      - name: Install dependencies
        run: npm ci      

      - name: 'change version'
        run: |
        TOTO=$(npm version ${{github.event.inputs.version}} -m "Release %s")
        npm push --tags
        
