name: List branches and run matrix jobs

on:
  workflow_dispatch:

jobs:
  list-branches:
    runs-on: ubuntu-20.04
    outputs:
      branches: ${{ steps.listBranches.outputs.branches }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          token: ${{secrets.GH_PERSONNAL_ACCES_TOKEN}}
      - name: List branches on repo./sitory
        uses: ./.github/actions/list-branches
        with:
          branches_list:  "main test_master"
        id: listBranches
  display_branch_name:
    runs-on: ubuntu-20.04    
    needs: list-branches
    strategy:
      max-parallel: 2
      fail-fast: false
      matrix:
        branch: ${{ fromJSON(needs.list-branches.outputs.branches) }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}
          path: ./repo
          fetch-depth: '1'
      - name: Display branche name
        run: echo "I'm come form ${{ matrix.branch}} branch."