name: Propagate documentation content upwards
on:
  workflow_dispatch:

jobs:
  propagate-doc-upwards:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          path: ./labs
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          repository: benjaminParisel/gh-pr-diff-checker
          token: ${{ secrets.GH_PERSONNAL_ACCES_TOKEN }}
          path: ./gh-pr-diff-checker

      - name: Run propagate script
        run: |          
          cd ./gh-pr-diff-checker
          
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          # allow to keep our changes when merge=ours specified in .gitattributes
          git config merge.ours.driver true          
          
          ## merge each branch
          
          echo "########################################"
          echo "Performing the doc propagation"
          echo "########################################"
          
          chmod +x ./../labs/src/propagate-doc.sh
          ./../labs/src/propagate-doc.sh     

      - name: Send message to Slack channel
        if: failure()
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: 'C02J5M4JMK7'
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":fire:  Propagation documentation upwards failed. \n \n  @channel *We need you*, react with :fire_extinguisher: when you resolve the conflicts, and by :sweat_drops: when it will be done."
                  }
                },
                {
                  "type": "divider"
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "For more details, see <https://github.com/${{github.repository}}/runs/${{github.run_id}}?check_suite_focus=true|this is a link>"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":female-firefighter: Good luck my friend :male-firefighter: "
                  }
                }
              ]
            }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}