name: Propagate documentation content upwards
on:
  workflow_dispatch:

jobs:
  propagate-doc-upwards:
    runs-on: ubuntu-20.04
    env:
      bonita-slack-channel-id: 'C02J5M4JMK7'
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          path: ./labs
      - name: Setup checkout
        uses: actions/checkout@v2
        with:
          repository: benjaminParisel/gh-pr-diff-checker
          token: ${{ secrets.GH_PERSONNAL_ACCES_TOKEN }}
          path: ./gh-pr-diff-checker

      - name: Run propagate script
        run: |          
          cd ./gh-pr-diff-checker
          
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
          
          # allow to keep our changes when merge=ours specified in .gitattributes
          git config merge.ours.driver true          
          
          ## merge each branch
          
          echo "########################################"
          echo "Performing the doc propagation"
          echo "########################################"
          
          chmod +x ./../labs/src/propagate-doc.sh
          ./../labs/src/propagate-doc.sh     

      - name: Send message to Slack channel
        if: failure()
        uses: slackapi/slack-github-action@v1.17.0
        with:
          channel-id: ${{bonita-slack-channel-id}}
          payload: |
            {
            "blocks": [
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":fire:  Propagation documentation upwards failed. \n \n  @channel *We need someone* ! \n  - Add a :fire_extinguisher:if you take the action to resolve the conflicts (only one person is required) \n - Add a :sweat_drops: when it’s done (and eventually a :party_parrot: )"
                }
              },
              {
                "type": "divider"
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": "More details <https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}?check_suite_focus=true| here>"
                }
              },
              {
                "type": "section",
                "text": {
                  "type": "mrkdwn",
                  "text": ":female-firefighter: Good luck my friend :male-firefighter: "
                }
              }
            ]
          }
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}